package com.aiassist.draft;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Map;

import com.aiassist.config.OllamaProperties;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Primary;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;

/**
 * Drafts content with a locally running open-source LLM served by Ollama
 * (https://ollama.com). Enabled with {@code ai-assist.ollama.enabled=true};
 * if the call fails, drafting falls back to the template engine so a draft
 * is always produced.
 */
@Component
@Primary
@ConditionalOnProperty(prefix = "ai-assist.ollama", name = "enabled", havingValue = "true")
public class OllamaContentDrafter implements ContentDrafter {

    private static final Logger log = LoggerFactory.getLogger(OllamaContentDrafter.class);

    private final RestClient restClient;
    private final OllamaProperties properties;
    private final TemplateContentDrafter fallback;

    public OllamaContentDrafter(OllamaProperties properties, TemplateContentDrafter fallback) {
        this.properties = properties;
        this.fallback = fallback;
        SimpleClientHttpRequestFactory requestFactory = new SimpleClientHttpRequestFactory();
        requestFactory.setConnectTimeout(Duration.ofSeconds(10));
        requestFactory.setReadTimeout(Duration.ofSeconds(properties.timeoutSeconds()));
        this.restClient = RestClient.builder()
                .baseUrl(properties.baseUrl())
                .requestFactory(requestFactory)
                .build();
    }

    record OllamaResponse(String response) {
    }

    @Override
    public Draft draft(String topic, String transcript, DraftOptions options) {
        try {
            String prompt = buildPrompt(topic, transcript, options);
            OllamaResponse result = restClient.post()
                    .uri("/api/generate")
                    .body(Map.of("model", properties.model(), "prompt", prompt, "stream", false))
                    .retrieve()
                    .body(OllamaResponse.class);
            if (result == null || result.response() == null || result.response().isBlank()) {
                log.warn("Ollama returned an empty response; falling back to template drafter");
                return fallback.draft(topic, transcript, options);
            }
            String text = result.response().strip();
            return new Draft(topic, options.contentType().name(), options.tone().name(),
                    "Draft generated by model " + properties.model() + ".",
                    List.of(new Draft.Section("Draft", text)),
                    List.of(), List.of(), text, name(), Instant.now(), null);
        } catch (RuntimeException e) {
            log.warn("Ollama drafting failed ({}); falling back to template drafter", e.getMessage());
            return fallback.draft(topic, transcript, options);
        }
    }

    @Override
    public String name() {
        return "ollama:" + properties.model();
    }

    private String buildPrompt(String topic, String transcript, DraftOptions options) {
        return """
                You are a writing assistant. Using the notes below, write a detailed %s \
                in a %s tone about "%s". Structure it with a title, a short summary, \
                well-organized sections, and (if relevant) action items.

                Notes:
                %s
                """.formatted(options.contentType().name().toLowerCase().replace('_', ' '),
                options.tone().name().toLowerCase(), topic, transcript);
    }
}
